server:
  port: 8765

management:
  security:
    enabled: false

info:
  component: DEMO API Gateway Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

ribbon:
  eurekaEnabled: true

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    appname: demo-api-gateway-service
    preferIpAddress: true

zuul:
  prefix: /api
  routes:
    gtd:
      path: /**

  spring:
    sleuth:
      sampler:
        percentage: 1.0
      web:
        skipPattern: (^cleanup.*)