#!/bin/bash

#docker build -t kafka-event-sourcing-app/kafka kafka/
#docker build -t kafka-event-sourcing-app/trifecta trifecta/
#docker build -t kafka-event-sourcing-app/zookeeper zookeeper/
#docker build -t kafka-event-sourcing-app/kafka-manager kafka-manager
#docker build -t kafka-event-sourcing-app/demo-api-central-gateway-service ../demo-api-gateway-service
#docker build -t kafka-event-sourcing-app/demo-api-central-discovery-service ../demo-api-central-discovery-service
#docker build -t kafka-event-sourcing-app/demo-api-command-service ../demo-api-command-service
#docker build -t kafka-event-sourcing-app/demo-api-query-service ../demo-api-query-service
docker build -t kafka-event-sourcing-app/demo-api-central-zipkin-service ../demo-api-central-zipkin-service
#docker build -t kafka-event-sourcing-app/demo-api-central-config-service ../demo-api-central-config-service
