/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package demo.api.codec.kafka.events.serialization;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroItemConcluded extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = 775913681753536640L;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroItemConcluded\",\"namespace\":\"demo.api.codec.kafka.events.serialization\",\"fields\":[{\"name\":\"itemId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<AvroItemConcluded> ENCODER =
            new BinaryMessageEncoder<AvroItemConcluded>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<AvroItemConcluded> DECODER =
            new BinaryMessageDecoder<AvroItemConcluded>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     */
    public static BinaryMessageDecoder<AvroItemConcluded> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     */
    public static BinaryMessageDecoder<AvroItemConcluded> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<AvroItemConcluded>(MODEL$, SCHEMA$, resolver);
    }

    /** Serializes this AvroItemConcluded to a ByteBuffer. */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /** Deserializes a AvroItemConcluded from a ByteBuffer. */
    public static AvroItemConcluded fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    @Deprecated
    public java.lang.String itemId;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public AvroItemConcluded() {
    }

    /**
     * All-args constructor.
     * @param itemId The new value for itemId
     */
    public AvroItemConcluded(java.lang.String itemId) {
        this.itemId = itemId;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return itemId;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                itemId = (java.lang.String) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'itemId' field.
     * @return The value of the 'itemId' field.
     */
    public java.lang.String getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the 'itemId' field.
     * @param value the value to set.
     */
    public void setItemId(java.lang.String value) {
        this.itemId = value;
    }

    /**
     * Creates a new AvroItemConcluded RecordBuilder.
     * @return A new AvroItemConcluded RecordBuilder
     */
    public static demo.api.codec.kafka.events.serialization.AvroItemConcluded.Builder newBuilder() {
        return new demo.api.codec.kafka.events.serialization.AvroItemConcluded.Builder();
    }

    /**
     * Creates a new AvroItemConcluded RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new AvroItemConcluded RecordBuilder
     */
    public static demo.api.codec.kafka.events.serialization.AvroItemConcluded.Builder newBuilder(demo.api.codec.kafka.events.serialization.AvroItemConcluded.Builder other) {
        return new demo.api.codec.kafka.events.serialization.AvroItemConcluded.Builder(other);
    }

    /**
     * Creates a new AvroItemConcluded RecordBuilder by copying an existing AvroItemConcluded instance.
     * @param other The existing instance to copy.
     * @return A new AvroItemConcluded RecordBuilder
     */
    public static demo.api.codec.kafka.events.serialization.AvroItemConcluded.Builder newBuilder(demo.api.codec.kafka.events.serialization.AvroItemConcluded other) {
        return new demo.api.codec.kafka.events.serialization.AvroItemConcluded.Builder(other);
    }

    /**
     * RecordBuilder for AvroItemConcluded instances.
     */
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroItemConcluded>
            implements org.apache.avro.data.RecordBuilder<AvroItemConcluded> {

        private java.lang.String itemId;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(demo.api.codec.kafka.events.serialization.AvroItemConcluded.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.itemId)) {
                this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
                fieldSetFlags()[0] = true;
            }
        }

        /**
         * Creates a Builder by copying an existing AvroItemConcluded instance
         * @param other The existing instance to copy.
         */
        private Builder(demo.api.codec.kafka.events.serialization.AvroItemConcluded other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.itemId)) {
                this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
                fieldSetFlags()[0] = true;
            }
        }

        /**
         * Gets the value of the 'itemId' field.
         * @return The value.
         */
        public java.lang.String getItemId() {
            return itemId;
        }

        /**
         * Sets the value of the 'itemId' field.
         * @param value The value of 'itemId'.
         * @return This builder.
         */
        public demo.api.codec.kafka.events.serialization.AvroItemConcluded.Builder setItemId(java.lang.String value) {
            validate(fields()[0], value);
            this.itemId = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'itemId' field has been set.
         * @return True if the 'itemId' field has been set, false otherwise.
         */
        public boolean hasItemId() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'itemId' field.
         * @return This builder.
         */
        public demo.api.codec.kafka.events.serialization.AvroItemConcluded.Builder clearItemId() {
            itemId = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public AvroItemConcluded build() {
            try {
                AvroItemConcluded record = new AvroItemConcluded();
                record.itemId = fieldSetFlags()[0] ? this.itemId : (java.lang.String) defaultValue(fields()[0]);
                return record;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<AvroItemConcluded>
            WRITER$ = (org.apache.avro.io.DatumWriter<AvroItemConcluded>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<AvroItemConcluded>
            READER$ = (org.apache.avro.io.DatumReader<AvroItemConcluded>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

}
